[project]
name = "weight-score-calculator-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.9.2",
    "streamlit==1.40.1",
    "watchdog>=6.0.0",
]
